<a href="https://colab.research.google.com/github/alinarogova/HW/blob/master/%D0%94%D0%97_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпорт модулів

In [11]:
import pandas as pd

Дані медичне страхування

In [12]:
# трохи обробки даних
df = pd.read_csv('https://raw.githubusercontent.com/HalyshAnton/IT-Step-Pyton-AI/main/module3/data/insurance.csv')

df['sex'] = df['sex'].map({'male': 0, 'female':1})
df['smoker'] = df['smoker'].map({'no': 0, 'yes':1})

df = df.drop(columns=['region'])

data = df[['age', 'bmi', 'expenses']]
df[['age', 'bmi', 'expenses']] = (data - data.min()) / (data.max() - data.min())

In [13]:
df.head()

age  sex       bmi  children  smoker  expenses
0  0.021739    1  0.320755         0       1  0.251611
1  0.000000    0  0.479784         1       0  0.009636
2  0.217391    0  0.458221         3       0  0.053115
3  0.326087    0  0.180593         0       0  0.333010
4  0.304348    0  0.347709         0       0  0.043816

Потрібно на основі інформації людини спрогнозувати розмір її страховки `expenses`

# Завдання 1
Створіть клас Dataset

In [14]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"


In [15]:
X = df.drop(columns='expenses')
y = df['expenses']

In [19]:

from torch.utils.data import Dataset

class myDataset(Dataset):
  def __init__(self, X, y):
    super().__init__()
    self.X = torch.tensor(X.values, dtype=torch.float32)
    self.y = torch.tensor(y.values, dtype=torch.float32)
    self.y = self.y.reshape(-1, 1)

  def __len__(self):
    return len(self.X)

  def __getitem__(self, idx):
    return self.X[idx], self.y[idx]

data = myDataset(X, y)
data[-1]

(tensor([0.9348, 1.0000, 0.3531, 0.0000, 1.0000]), tensor([0.4472]))

# Завдання 2
Створіть DataLoader. Перевірте розміри даних в першому пакеті. Розмір пакетів оберіть самостійно

In [23]:
from torch.utils.data import DataLoader

loader = DataLoader(data, batch_size = 32, shuffle=True)

for X, y in loader:
  print(X)
  break
X = X.to(device)
X

tensor([[0.8478, 1.0000, 0.4933, 2.0000, 0.0000],
        [0.5000, 0.0000, 0.6550, 0.0000, 0.0000],
        [0.0870, 0.0000, 0.5822, 1.0000, 1.0000],
        [0.0000, 0.0000, 0.3369, 0.0000, 0.0000],
        [0.0435, 0.0000, 0.3208, 0.0000, 0.0000],
        [0.1304, 1.0000, 0.2857, 0.0000, 0.0000],
        [0.0870, 0.0000, 0.2480, 0.0000, 0.0000],
        [0.1957, 1.0000, 0.2372, 0.0000, 1.0000],
        [0.0217, 1.0000, 0.3342, 1.0000, 0.0000],
        [0.4565, 0.0000, 0.4879, 2.0000, 0.0000],
        [0.5217, 1.0000, 0.2857, 0.0000, 1.0000],
        [0.0000, 0.0000, 0.3612, 1.0000, 0.0000],
        [0.1739, 1.0000, 0.0323, 2.0000, 1.0000],
        [0.1957, 0.0000, 0.3369, 0.0000, 1.0000],
        [0.3043, 0.0000, 0.5714, 2.0000, 0.0000],
        [0.7826, 0.0000, 0.2561, 1.0000, 0.0000],
        [0.6739, 0.0000, 0.3720, 1.0000, 0.0000],
        [0.3913, 0.0000, 0.3693, 0.0000, 0.0000],
        [0.8261, 1.0000, 0.3315, 0.0000, 0.0000],
        [0.3043, 1.0000, 0.3477, 0.0000, 0.0000],


tensor([[0.8478, 1.0000, 0.4933, 2.0000, 0.0000],
        [0.5000, 0.0000, 0.6550, 0.0000, 0.0000],
        [0.0870, 0.0000, 0.5822, 1.0000, 1.0000],
        [0.0000, 0.0000, 0.3369, 0.0000, 0.0000],
        [0.0435, 0.0000, 0.3208, 0.0000, 0.0000],
        [0.1304, 1.0000, 0.2857, 0.0000, 0.0000],
        [0.0870, 0.0000, 0.2480, 0.0000, 0.0000],
        [0.1957, 1.0000, 0.2372, 0.0000, 1.0000],
        [0.0217, 1.0000, 0.3342, 1.0000, 0.0000],
        [0.4565, 0.0000, 0.4879, 2.0000, 0.0000],
        [0.5217, 1.0000, 0.2857, 0.0000, 1.0000],
        [0.0000, 0.0000, 0.3612, 1.0000, 0.0000],
        [0.1739, 1.0000, 0.0323, 2.0000, 1.0000],
        [0.1957, 0.0000, 0.3369, 0.0000, 1.0000],
        [0.3043, 0.0000, 0.5714, 2.0000, 0.0000],
        [0.7826, 0.0000, 0.2561, 1.0000, 0.0000],
        [0.6739, 0.0000, 0.3720, 1.0000, 0.0000],
        [0.3913, 0.0000, 0.3693, 0.0000, 0.0000],
        [0.8261, 1.0000, 0.3315, 0.0000, 0.0000],
        [0.3043, 1.0000, 0.3477, 0.0000, 0.0000],


# Завдання 3
Створіть нейромережу:
* Кількість шарів оберіть між 1-5
* Виберіть різні функції активації: Relu, LeakyRelu
* Кілкість нейронів у прихованих шарах повинна **не зростати**

In [26]:
from torch import nn

model = nn.Sequential(
    nn.Linear(5, 60),
    nn.ReLU(),
    nn.Linear(60, 30),
    nn.ReLU(),
    nn.Linear(30, 15),
    nn.ReLU(),
    nn.Linear(15, 1)

)

# Завдання 4
Визначте функцію втрат та оптимізатор

In [27]:
loss_fn = nn.MSELoss()

optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

# Завдання 5
Натренуйте нейромережу. візміть невелику кількість епох

In [28]:
import numpy as np
epoches = 5

for i in range(epoches):
  for X, y in loader:
    y = y.to(device)
    X = X.to(device)

    y_pred = model(X)

    loss = loss_fn(y_pred, y)

    loss.backward() # рахуємо градієнти
    optimizer.step()
    optimizer.zero_grad()
  print(loss.item())

0.018622737377882004
0.008498131297528744
0.008107743225991726
0.007248610723763704
0.0038457470946013927


In [29]:
X, y = data[-1]
model = model.to("cpu")
model(X)

tensor([0.5668], grad_fn=<ViewBackward0>)

In [30]:
y

tensor([0.4472])

In [31]:

with torch.no_grad():
  X, y = data[-1]
  y_pred = model(X)
y_pred

tensor([0.5668])

In [32]:
from sklearn.metrics import r2_score
y_pred = []
y_ = []
for X, y in data:
  pred = model(X)
  y_pred.append(pred.item())
  y_.append(y)
r2 = r2_score(y_, y_pred)
r2

0.839335696541675