<a href="https://colab.research.google.com/github/alinarogova/HW/blob/master/%D0%94%D0%97_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [4]:
import numpy as np

#Завдання 1

Створіть масив з парними числами між 30 і 70

In [2]:
x = np.array(range(30, 71, 2))
x

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

#Завдання 2
Створіть масив з 10 числами між 0(включно) та 1(не включно) див документацію np.linspace

In [3]:
x = np.linspace(0, 1, 10, endpoint=False)
x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#Завдання 4
Напишіть функцію яка приймає матрицю розміру nxn та повертає матрицю розміру (n+2) x (n+2), на краях якої розміщенні 0.

In [4]:
n = 2
x = np.array(range(1, 5)).reshape(2,2)
print(x)

def padding(matrix):
  n = matrix.shape[0]
  new_shape = (n+2, n+2)
  res_matrix = np.zeros(new_shape, dtype=matrix.dtype)
  res_matrix[1:-1, 1:-1] = matrix
  return res_matrix
y = padding(x)
print(y)

[[1 2]
 [3 4]]
[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


#Завдання 5
У попередьньому масиві змініть тип даних. Виведіть тип даних до та після зміни

In [5]:
print("Було:", y.dtype)
y = y.astype(np.float64)
print("Стало:", y.dtype)

Було: int64
Стало: float64


#Завдання 6
У даному масиві замініть елементи, які дорівнюють\більші\менші за var на -1

In [8]:
x = np.array([1, 5, 3, 8, 6, 5, 7, 4])
var = 5
x_eq = np.where(x == var, -1, x)
x_more = np.where(x > var, -1, x)
x_less = np.where(x < var, -1, x)
print(x_eq, x_more, x_less)


[ 1 -1  3  8  6 -1  7  4] [ 1  5  3 -1 -1  5 -1  4] [-1  5 -1  8  6  5  7 -1]


In [7]:
x[x==var]=-1
x

array([ 1, -1,  3,  8,  6, -1,  7,  4])

In [9]:
x[x>var]=-1
x

array([ 1,  5,  3, -1, -1,  5, -1,  4])

In [10]:
x[x<var]=-1
x

array([-1,  5, -1, -1, -1,  5, -1, -1])

#Завдання 7
Замініть пропущені значення матриці(np.nan) на -1

Дивись np.isnan

In [11]:
X = np.array([[1, 2, np.nan, 4],
              [5, np.nan, np.nan, 4],
              [np.nan, 10, 11, np.nan]])
X[np.isnan(X)]=-1
X

array([[ 1.,  2., -1.,  4.],
       [ 5., -1., -1.,  4.],
       [-1., 10., 11., -1.]])

#Завдання 8
Створіть матрицю розміру 4х6 з випадковими числами. Змініть її розмір на 3х8

In [12]:
x = np.random.randint(0, 100, (4,6))
x = x.reshape((3, 8))
x

array([[94, 12, 75, 42, 31, 80, 35, 82],
       [98, 94,  7, 19,  7, 42, 53,  7],
       [92,  6, 38, 35, 67,  6, 96, 63]])

#Завдання 9
Створіть випадкову матрицю розміром 3х4. Знайдіть середнє арифметичне(mean) кожного стовпчика

In [13]:
x = np.random.randint(1, 10, (3,4))
print(x)
x.mean(axis=0)

[[5 4 1 3]
 [3 6 7 6]
 [7 6 1 2]]


array([5.        , 5.33333333, 3.        , 3.66666667])

#Завдання 10
Є матриця з ймовірностями того, що зображення(рядки) належить певному класу(стовпчики). Для кожного зображення(рядка) знайдіть індекс класу(стовпчика) з найбільшою ймовірністю

In [17]:
x = np.array([[0.2 , 0.3 , 0.23, 0.07, 0.03, 0.17],
              [0.15, 0.06, 0.21, 0.12, 0.24, 0.24],
              [0.1 , 0.21, 0.03, 0.07, 0.31, 0.28],
              [0.21, 0.24, 0.03, 0.18, 0.12, 0.21],
              [0.19, 0.25, 0.25, 0.06, 0.12, 0.12]])
x.max(axis=1)
x.argmax(axis = 1)

array([1, 4, 4, 1, 1])

Пояснення: в першому рядку найбільша ймовірність -- 0.3 під індексом 1

в другому рядку -- 0.24 під індексом 4

в третьому рядку -- 0.31 під індексом 4

в четвертому рядку -- 0.24 під індексом 1

в п'ятому рядку -- 0.25 під індексом 1(там є ще одне 0.25, але ми беремо те що з меншим індексом)


#Завдання 11
В даній матриці знайдіть всі елементи зі значенням між 3 і 6

Дивись документацію np.logical_and

In [20]:
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [9, 8, 7, 6, 5],
              [4, 3, 2, 1, 0]])
X[(X>3) & (X<6)]

array([4, 5, 5, 4])

#Завдання 12
Створіть випадкову матрицю розміру 5х6. Нормалізуйте стовпчики: від кожного елемента ставпчика відніміть мінімальне значення та поділіть результат на різницю між максимальним та мінімальним елементом цього стовпчика.

Після цього всі значення мають бути в межах [0, 1]

In [5]:
x=np.random.randint(1, 10, (5, 6))
x

array([[8, 6, 7, 8, 6, 8],
       [3, 1, 6, 2, 4, 1],
       [1, 9, 1, 1, 6, 2],
       [8, 3, 8, 9, 9, 2],
       [5, 8, 3, 2, 2, 2]])

In [8]:
x_min=x.min(axis=0 ,keepdims = True)
x_min

array([[1, 1, 1, 1, 2, 1]])

In [9]:
(x-x_min)/(x.max(axis=0 ,keepdims = True)-x_min)

array([[1.        , 0.625     , 0.85714286, 0.875     , 0.57142857,
        1.        ],
       [0.28571429, 0.        , 0.71428571, 0.125     , 0.28571429,
        0.        ],
       [0.        , 1.        , 0.        , 0.        , 0.57142857,
        0.14285714],
       [1.        , 0.25      , 1.        , 1.        , 1.        ,
        0.14285714],
       [0.57142857, 0.875     , 0.28571429, 0.125     , 0.        ,
        0.14285714]])