<a href="https://colab.research.google.com/github/alinarogova/HW/blob/master/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BD%D0%B5%D0%B9%D1%80%D0%BE%D0%BC%D0%B5%D1%80%D0%B5%D0%B6%D1%96.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпорт модулів

In [1]:
import pandas as pd

Дані про морське вухо(молюск)

<div>
<img src="https://m.media-amazon.com/images/I/81-FC5TlLtL.jpg" width="500"/>
</div>

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/HalyshAnton/IT-Step-Pyton-AI/main/module3/data/abalone.csv')
df.drop(columns=['Type', 'WholeWeight', 'ShuckedWeight', 'VisceraWeight', 'ShellWeight'], inplace=True)

In [3]:
df.head()

LongestShell  Diameter  Height  Rings
0         0.455     0.365   0.095     15
1         0.350     0.265   0.090      7
2         0.530     0.420   0.135      9
3         0.440     0.365   0.125     10
4         0.330     0.255   0.080      7

Потрібно на основі розмірів молюска спрогнозувати кількість кілець в мушлі `Rings`. Використовуйте процесор cpu

# Завдання 1
Створіть клас Dataset

In [4]:
import torch
import pandas as pd

device = "cuda" if torch.cuda.is_available() else "cpu"


In [17]:
device

'cuda'

In [5]:
from torch.utils.data import Dataset

class MyClass(Dataset):
  def __init__(self, X, y):
    super().__init__()
    self.X = torch.tensor(X.values, dtype=torch.float32)
    self.y = torch.tensor(y.values, dtype=torch.float32)
    self.y = self.y.reshape(-1, 1)

  def __len__(self):
    return len(self.X)

  def __getitem__(self, idx):
    return self.X[idx], self.y[idx]

X = df.drop(columns="Rings")
y = df['Rings']

data = MyClass(X, y)

data[-1]

(tensor([0.7100, 0.5550, 0.1950]), tensor([12.]))

# Завдання 2
Створіть DataLoader. Перевірте розміри даних в першому пакеті. Розмір пакетів оберіть самостійно

In [6]:
from torch.utils.data import DataLoader

loader = DataLoader(data, batch_size = 32, shuffle=True)


In [20]:
for X, y in loader:
  print(X)
  break
X = X.to(device)
X

tensor([[0.5800, 0.4750, 0.1500],
        [0.6900, 0.5250, 0.1900],
        [0.3900, 0.3000, 0.0950],
        [0.5500, 0.4300, 0.1400],
        [0.6400, 0.4800, 0.1450],
        [0.2750, 0.2000, 0.0650],
        [0.5150, 0.4000, 0.1250],
        [0.4750, 0.3750, 0.1100],
        [0.5150, 0.4350, 0.1700],
        [0.4250, 0.3350, 0.1000],
        [0.5200, 0.3850, 0.1650],
        [0.6800, 0.5800, 0.2000],
        [0.4700, 0.3450, 0.1150],
        [0.7100, 0.5450, 0.1750],
        [0.3700, 0.2800, 0.0900],
        [0.5700, 0.4400, 0.1200],
        [0.6900, 0.5250, 0.1750],
        [0.5500, 0.4200, 0.1600],
        [0.5200, 0.4300, 0.1500],
        [0.4800, 0.3900, 0.1450],
        [0.5800, 0.4800, 0.1800],
        [0.6200, 0.4700, 0.1350],
        [0.5800, 0.4600, 0.1650],
        [0.7150, 0.5650, 0.2400],
        [0.5850, 0.4150, 0.1550],
        [0.4450, 0.3500, 0.1300],
        [0.5950, 0.4550, 0.1550],
        [0.3450, 0.2550, 0.0950],
        [0.6450, 0.5000, 0.1550],
        [0.400

tensor([[0.5800, 0.4750, 0.1500],
        [0.6900, 0.5250, 0.1900],
        [0.3900, 0.3000, 0.0950],
        [0.5500, 0.4300, 0.1400],
        [0.6400, 0.4800, 0.1450],
        [0.2750, 0.2000, 0.0650],
        [0.5150, 0.4000, 0.1250],
        [0.4750, 0.3750, 0.1100],
        [0.5150, 0.4350, 0.1700],
        [0.4250, 0.3350, 0.1000],
        [0.5200, 0.3850, 0.1650],
        [0.6800, 0.5800, 0.2000],
        [0.4700, 0.3450, 0.1150],
        [0.7100, 0.5450, 0.1750],
        [0.3700, 0.2800, 0.0900],
        [0.5700, 0.4400, 0.1200],
        [0.6900, 0.5250, 0.1750],
        [0.5500, 0.4200, 0.1600],
        [0.5200, 0.4300, 0.1500],
        [0.4800, 0.3900, 0.1450],
        [0.5800, 0.4800, 0.1800],
        [0.6200, 0.4700, 0.1350],
        [0.5800, 0.4600, 0.1650],
        [0.7150, 0.5650, 0.2400],
        [0.5850, 0.4150, 0.1550],
        [0.4450, 0.3500, 0.1300],
        [0.5950, 0.4550, 0.1550],
        [0.3450, 0.2550, 0.0950],
        [0.6450, 0.5000, 0.1550],
        [0.400

# Завдання 3
Створіть нейромережу:
* Кількість шарів оберіть між 1-3
* Виберіть різні функції активації: Relu, LeakyRelu, Swish
* Кілкість нейронів у прихованих шарах повинна **не зростати**

In [23]:
from torch import nn


model = nn.Sequential(
    nn.Linear(3, 6),
    nn.ReLU(),
    nn.Linear(6, 2),
    nn.ReLU(),
    nn.Linear(2, 1)
)
model = model.to(device)
model

Sequential(
  (0): Linear(in_features=3, out_features=6, bias=True)
  (1): ReLU()
  (2): Linear(in_features=6, out_features=2, bias=True)
  (3): ReLU()
  (4): Linear(in_features=2, out_features=1, bias=True)
)

# Завдання 4
Визначте функцію втрат та оптимізатор

In [9]:
# Функція втрат середньоквадратичної помилки (MSE) для регресії
loss_fn = nn.MSELoss()

# Оптимізатор (SGD) для оновлення ваг моделі
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

# Завдання 5
Натренуйте нейромережу. візміть невелику кількість епох

In [25]:
import numpy as np
epoches = 10

for i in range(epoches):
  for X, y in loader:
    y = y.to(device)
    X = X.to(device)

    y_pred = model(X)

    loss = loss_fn(y_pred, y)

    loss.backward() # рахуємо градієнти
    optimizer.step()
    optimizer.zero_grad()
  print(loss.item())


139.62298583984375
84.35952758789062
108.41650390625
92.13652801513672
120.7457504272461
84.55247497558594
126.62470245361328
130.8494415283203
105.71051025390625
110.08464813232422


In [26]:
y_pred

tensor([[-0.1435],
        [-0.1450],
        [-0.1317],
        [-0.1387],
        [-0.1355],
        [-0.1325],
        [-0.1305],
        [-0.1352],
        [-0.1425],
        [-0.1392],
        [-0.1333],
        [-0.1389],
        [-0.1376],
        [-0.1366],
        [-0.1365],
        [-0.1372],
        [-0.1312]], device='cuda:0', grad_fn=<AddmmBackward0>)

# Завдання 6
Збережіть нейромережу та зробіть прогноз

In [28]:
X, y = data[-1]
model = model.to("cpu")
model(X)

tensor([-0.1439], grad_fn=<ViewBackward0>)

In [29]:
y

tensor([12.])

In [30]:
with torch.no_grad():
  X, y = data[-1]
  y_pred = model(X)
y_pred

tensor([-0.1439])

In [15]:
y_pred.shape

torch.Size([1])

In [16]:
y.shape

torch.Size([1])

In [35]:
from sklearn.metrics import r2_score
y_pred = []
y_ = []
for X, y in data:
  pred = model(X)
  y_pred.append(pred.item())
  y_.append(y)
r2 = r2_score(y_, y_pred)
r2

-9.759548807781286